
from transformers import pipeline

sentiment_pipeline = pipeline("sentiment-analysis")

reviews = [
"This place was truly a wonderful surprise. The atmosphere, interior design, service and staff were all top-notch. Friendly, warm and welcoming in every way. We visited as a couple to celebrate my boyfriend’s birthday. I had mentioned this in advance and to our delight there was a small, thoughtful birthday note waiting for him on our table. Such a lovely personal touch! The food was absolutely outstanding. The portions were generous and the flavors were simply unforgettable. The beef with teriyaki sauce and the wagyu fried rice are still lingering on our taste buds. The wine was delicious and the service throughout the evening was relaxed, attentive and genuinely kind. To end the night, my boyfriend was surprised with a small dessert and a sparkling candle, which made the celebration feel extra special. We had a truly cozy and memorable evening and will definitely be coming back." ,
    "One of the greatest experiences we’ve had in 2023! From the start you’re feeling like you’re in a secret world. A mint service, great food, great wine and a fantastic location. What do you need more? A big 5 star ⭐️ review!",
    "Nice atmosphere and staff. However the food was hit and miss and I ended up with food poisoning hence the one star. Long wait between each dish and quite overpriced for quality and quantity. Not a bad experience overall, but I wouldn’t recommend to come for more than drinks.",
    "LWe were visiting Amsterdam and, after some research, booked Secret Garden in advance for our Christmas Eve dinner — and it absolutely did not disappoint. From the moment we stepped inside, we were genuinely wowed. The decor and ambience are simply magical — cozy yet elegant, with a beautiful blend of natural elements and contemporary design. The space feels intimate and warm, almost like stepping into a hidden sanctuary in the city. The lighting is especially well done, soft and flattering, creating a relaxed, romantic atmosphere that makes you want to slow down and truly enjoy the evening. The staff were outstanding — warm, friendly, and genuinely attentive throughout the night. Service felt polished yet personal, never rushed and never intrusive. For Christmas Eve, the restaurant offered a set menu, and every single dish was a pleasant surprise. Each course wow-ed our palate — beautifully presented, full of flavour, and perfectly balanced. You can really tell that a lot of thought went into the seasoning and composition of each dish. It was honestly one of the best meals we’ve ever had, and this is one of those experiences where words don’t fully do it justice — you really have to experience it yourself. The waiter took the time to explain every dish, which added so much to the overall dining experience. It felt immersive and thoughtful, rather than just a meal. The drink menu is equally impressive, with a great selection of wines, cocktails, spirits, and even 0% alcohol options for non-drinkers — a very sweet and inclusive touch that we truly appreciated. Overall: Secret Garden delivers on every level — ambience, service, food, and experience. A perfect choice for a special occasion, especially festive dinners. Strongly recommended, and definitely a restaurant we would return to without hesitation.",
    "Stunning restaurant. Looked amazing on arrival. Staff was super friendly and attentive. Now the food!! Where to start... this place is pricey however the flavours and quality is unreal. We had the sable fish (black cod), ribeye steak, fried rice, lomo saltado, chicken skewers which were a show stopper - we ordered 8 of them! All incredible. Cocktails were tasty too. Would 100% and return."
]

for review in reviews:
    result = sentiment_pipeline(review[:512])[0]
    print(f"{review[:80]}...\nLabel: {result['label']}, Score: {result['score']:.4f}\n")